# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aranya/paper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aranya/paper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aranya/paper/CMakeFiles /home/aranya/paper/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aranya/paper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named harris

# Build rule for target.
harris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harris
.PHONY : harris

# fast build rule for target.
harris/fast:
	$(MAKE) -f CMakeFiles/harris.dir/build.make CMakeFiles/harris.dir/build
.PHONY : harris/fast

#=============================================================================
# Target rules for targets named harris2

# Build rule for target.
harris2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harris2
.PHONY : harris2

# fast build rule for target.
harris2/fast:
	$(MAKE) -f CMakeFiles/harris2.dir/build.make CMakeFiles/harris2.dir/build
.PHONY : harris2/fast

src/harriscorner.o: src/harriscorner.cpp.o
.PHONY : src/harriscorner.o

# target to build an object file
src/harriscorner.cpp.o:
	$(MAKE) -f CMakeFiles/harris.dir/build.make CMakeFiles/harris.dir/src/harriscorner.cpp.o
.PHONY : src/harriscorner.cpp.o

src/harriscorner.i: src/harriscorner.cpp.i
.PHONY : src/harriscorner.i

# target to preprocess a source file
src/harriscorner.cpp.i:
	$(MAKE) -f CMakeFiles/harris.dir/build.make CMakeFiles/harris.dir/src/harriscorner.cpp.i
.PHONY : src/harriscorner.cpp.i

src/harriscorner.s: src/harriscorner.cpp.s
.PHONY : src/harriscorner.s

# target to generate assembly for a file
src/harriscorner.cpp.s:
	$(MAKE) -f CMakeFiles/harris.dir/build.make CMakeFiles/harris.dir/src/harriscorner.cpp.s
.PHONY : src/harriscorner.cpp.s

src/harriscornertracker.o: src/harriscornertracker.cpp.o
.PHONY : src/harriscornertracker.o

# target to build an object file
src/harriscornertracker.cpp.o:
	$(MAKE) -f CMakeFiles/harris2.dir/build.make CMakeFiles/harris2.dir/src/harriscornertracker.cpp.o
.PHONY : src/harriscornertracker.cpp.o

src/harriscornertracker.i: src/harriscornertracker.cpp.i
.PHONY : src/harriscornertracker.i

# target to preprocess a source file
src/harriscornertracker.cpp.i:
	$(MAKE) -f CMakeFiles/harris2.dir/build.make CMakeFiles/harris2.dir/src/harriscornertracker.cpp.i
.PHONY : src/harriscornertracker.cpp.i

src/harriscornertracker.s: src/harriscornertracker.cpp.s
.PHONY : src/harriscornertracker.s

# target to generate assembly for a file
src/harriscornertracker.cpp.s:
	$(MAKE) -f CMakeFiles/harris2.dir/build.make CMakeFiles/harris2.dir/src/harriscornertracker.cpp.s
.PHONY : src/harriscornertracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... harris"
	@echo "... harris2"
	@echo "... rebuild_cache"
	@echo "... src/harriscorner.o"
	@echo "... src/harriscorner.i"
	@echo "... src/harriscorner.s"
	@echo "... src/harriscornertracker.o"
	@echo "... src/harriscornertracker.i"
	@echo "... src/harriscornertracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

